server:
  port: 8081
  servlet:
    context-path: gateway
spring:
  data:
    mongodb:
      host: localhost
      database: monkey-game
    redis:
      database: 0

monkey:
  server-infos:
    - code: hall
      names: 1
  wechat:
    app-id: wx7552e679690359f5
    secret: 79d6275e6a44de21a4bf6c7d9c8dd2d9