server:
  port: 8084
  servlet:
    context-path: /system
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  data:
    mongodb:
      host: localhost
      database: system